# Generated by Django 5.1.7 on 2025-04-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminCare', '0002_faq_tag_document_user_helpdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdocument',
            name='summary',
            field=models.TextField(blank=True, help_text='Resumen breve u opcional', null=True),
        ),
        migrations.AlterField(
            model_name='helpdocument',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='help_documents', to='appAdminCare.tag'),
        ),
    ]
