# Generated by Django 5.1.7 on 2025-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminCare', '0003_helpdocument_summary_alter_helpdocument_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpdocument',
            name='content',
        ),
        migrations.AddField(
            model_name='helpdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Sube el archivo en PDF', null=True, upload_to='help_docs/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Sube el archivo', upload_to='documents/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='helpdocument',
            name='summary',
            field=models.TextField(blank=True, help_text='Escribe un breve resumen del documento', null=True, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='helpdocument',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='help_documents', to='appAdminCare.tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='helpdocument',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
