# Generated by Django 5.1.7 on 2025-04-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminCare', '0004_remove_helpdocument_content_helpdocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='documents_covers/', verbose_name='Portada'),
        ),
    ]
