# Generated by Django 5.1.7 on 2025-04-24 11:20

import appAdminCare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminCare', '0005_document_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=appAdminCare.models.MediaStorage(), upload_to='documents_covers/', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Sube el archivo', storage=appAdminCare.models.MediaStorage(), upload_to='documents/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='helpdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Sube el archivo en PDF', null=True, storage=appAdminCare.models.MediaStorage(), upload_to='help_docs/', verbose_name='Archivo PDF'),
        ),
    ]
