# Generated by Django 5.1.7 on 2025-05-20 01:53

import appAdminCare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminCare', '0006_alter_document_cover_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdocument',
            name='cover',
            field=models.ImageField(blank=True, help_text='Miniatura generada a partir de la primera página del PDF', null=True, storage=appAdminCare.models.MediaStorage(), upload_to='help_docs_covers/', verbose_name='Portada'),
        ),
    ]
