# Generated by Django 5.1.7 on 2025-05-20 02:29

import appAdminCare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminCare', '0007_helpdocument_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=appAdminCare.models.MediaStorage(), upload_to='documents_covers/', verbose_name='Portada (auto)'),
        ),
        migrations.AlterField(
            model_name='helpdocument',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=appAdminCare.models.MediaStorage(), upload_to='help_docs_covers/', verbose_name='Portada (auto)'),
        ),
    ]
