# Generated by Django 5.1.7 on 2025-05-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminCare', '0008_alter_document_cover_alter_helpdocument_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpdocument',
            name='summary',
        ),
    ]
